FinalExam/FinalExam.Web/Models/ErrorViewModel.cs
namespace FinalExam.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FinalExam/FinalExam.Web/Models/TroubleViewModel.cs
namespace FinalExam.Web.Models
{
    public class TroubleViewModel
    {
        public int PostalCode { get; set; }
        public string Street { get; set; }

        public string Number { get; set; }
        public DateTime TroubleDate { get; set; }
    }
}

FinalExam/FinalExam.Web/Controllers/HomeController.cs
using FinalExam.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FinalExam.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FinalExam/FinalExam.Web/Controllers/TroubleAddController.cs
using FinalExam.DB;
using FinalExam.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinalExam.Web.Controllers
{
    public class TroubleAddController : Controller
    {

        private readonly FinalExamDataDB fedbcontext;

        
        public TroubleAddController(FinalExamDataDB fedbcontext)
        {
            this.fedbcontext = fedbcontext;
        }
        

        public IActionResult Index()
        {
            return View();
        }

        /*
        public IActionResult TroubleAdd()
        {
            TroubleViewModel tm = new TroubleViewModel();
            tm.PostalCode = int.Parse(Request.Form["postalcode"]);
            tm.Street = Request.Form["street"];
            tm.Number = Request.Form["number"];
            tm.TroubleDate = DateTime.Now;
            return View(tm);

        }
        */

        
        //public IActionResult Submit(TroubleViewModel troubleRequest)
        public IActionResult TroubleAdd(TroubleViewModel troubleRequest)
        {

            Trouble trouble = new FinalExam.DB.Trouble()
            {
                PostalCode = troubleRequest.PostalCode,
                Street = troubleRequest.Street,
                Number = troubleRequest.Number,
                TroubleDate = DateTime.Now
            };

            fedbcontext.Troubles.Add(trouble);
            fedbcontext.SaveChanges();

            /*
            TroubleViewModel tm = new TroubleViewModel();
            tm.PostalCode = int.Parse(Request.Form["postalcode"]);
            tm.Street = Request.Form["street"];
            tm.Number = Request.Form["number"];
            tm.TroubleDate = DateTime.Now;
            */
            troubleRequest.TroubleDate = (DateTime)trouble.TroubleDate;

            return View(troubleRequest);
        }
        

    }
}

FinalExam/FinalExam.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FinalExam/FinalExam.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinalExam.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinalExam.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinalExam.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TroubleAdd" asp-action="Index">Hibabejelentés</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FinalExam.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FinalExam/FinalExam.Web/Views/TroubleAdd/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="mb-3">
    <h1 align="center">Hibabejelentés</h1>
</div>

<form action="TroubleAdd/troubleadd" method="post">
    <div class="col-sm-1">
        <label for="" class="form-label">Irányítószám</label>
        <input type="number" class="form-control" name="postalcode" required min="1000" max="9999" size="4" />
    </div>
    <div class="col-sm-8">
        <label for="" class="form-label">Utca</label>
        <input type="text" class="form-control" name="street" required minlength="1" />
    </div>
    <div class="col-sm-2">
        <label for="" class="form-label">Házszám</label>
        <input type="text" class="form-control" name="number" required minlength="1" />
    </div>
    <br/>
    <div class="mb-3">
        <button type="submit" class="btn btn-primary">Bejelentés</button>
    </div>
</form>

FinalExam/FinalExam.Web/Views/TroubleAdd/TroubleAdd.cshtml
@model TroubleViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Sikeres adatbeküldés
<br />
<br />
A kapott adatok:

<br />
Irányítószám: @Model.PostalCode

<br />
Utca: @Model.Street

<br />
Házszám: @Model.Number

<br />
Rögzítés dátuma: @Model.TroubleDate