MindigFenyes/MindigFenyes.Web/Models/ErrorViewModel.cs
namespace MindigFenyes.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MindigFenyes/MindigFenyes.Web/Models/TroubleViewModel.cs
namespace MindigFenyes.Web.Models
{
    public class TroubleViewModel
    {

        public int PostalCode { get; set; }

        public string Street { get; set; }

        public string Number  { get; set; }
    }
}

MindigFenyes/MindigFenyes.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MindigFenyes.Web.Models;
using System.Diagnostics;

namespace MindigFenyes.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MindigFenyes/MindigFenyes.Web/Controllers/TroubleController.cs
using Microsoft.AspNetCore.Mvc;
using MindigFenyes.DB;
using MindigFenyes.Web.Models;
using System.Net.Sockets;

namespace MindigFenyes.Web.Controllers
{
    public class TroubleController : Controller
    {

        private readonly MindigFenyesDBData mfcontext;

        public TroubleController(MindigFenyesDBData mfcontext)
        {
            this.mfcontext = mfcontext;
        }


        // public IActionResult Index()
        public IActionResult Trouble()
        {
            return View();
            /*
            TroubleViewModel tvm = new TroubleViewModel();
            tvm.PostalCode = Request.Form["psc"];
            // em.RogzitesDatuma = DateTime.Now;
            return View(tvm);
            */
        }


        public IActionResult Submit(TroubleViewModel ticketAddressRequest)
        {
            // Address? address = mfcontext.Addresses.SingleOrDefault(t => t.PostalCode == taskRequest.PostalCode && t.Street.Equals(ticketAddressRequest.Street) && t.Number == ticketAddressRequest.Number);


            // MindigFenyes.DB.Trouble trouble = new MindigFenyes.DB.Trouble()
            Trouble trouble = new MindigFenyes.DB.Trouble()
            { 
                /*
                Address = address ??= new Address
                {
                    PostalCode = taskRequest.ZipCode,
                    Street = taskRequest.Street,
                    Number = taskRequest.Number
                },
                */
                TroubleDate = DateTime.Now,
            };

            mfcontext.Troubles.Add(trouble);
            mfcontext.SaveChanges();

            return View();
        }

    }
}

MindigFenyes/MindigFenyes.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MindigFenyes.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MindigFenyes.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MindigFenyes.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trouble" asp-action="Trouble">Hibabejelentés</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MindigFenyes.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MindigFenyes/MindigFenyes.Web/Views/Trouble/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form action="bevitel" method="post">
    <input type="text" name="embernev" />
    <input type="submit" />
</form>

MindigFenyes/MindigFenyes.Web/Views/Trouble/Submit.cshtml
@model TroubleViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
Bejelentését rögzítettük!
<br />
<br />
A kapott adatok:
<br />
Irányító szám: 
<br />
Utca: 
<br />
Házszám: 
<br />


<form method="Post" action="/Trouble/Trouble">

    <button type="submit" class="btn btn-primary">Új hiba</button>
</form>

MindigFenyes/MindigFenyes.Web/Views/Trouble/Trouble.cshtml
@model TroubleViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="mb-3">
    <h1 align="center">Hibabejelentés</h1>
</div>

<form method="Post" action="/Trouble/Submit">
    <div class="mb-3">
        <label for="" class="form-label">Irányítószám</label>
        <input type="number" name="psc" class="form-control" size="10" asp-for="PostalCode">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Utca</label>
        <input type="text" class="form-control" size="50" asp-for="Street">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Házszám</label>
        <input type="number" class="form-control" size="10" asp-for="Number">
    </div>
    <button type="submit" class="btn btn-primary">Bejelentés</button>
</form>